var words = "[attribute],[attribute=value],attribute,value,border:,px,em,solid,-moz-,color:,top,top:,right,right:,left,left:,-webkit-,width:,height:,border-radius:,box-shadow:,red,blue,black,green,pink,orange,yellow,violet,indigo,lime,peru,darkSlateGray,gray,brown,olive,background:,url,-o-,font:,bold,verdana,resize:,none,background-color:,animation:,position:,absolute,initial,fixed,inherit,relative,static,z-index:,white-space:,pre-wrap,100%,50%,25%,75%,display:,inline-block,border-image:,border-top-image,border-right-image,border-bottom-image,border-left-image,border-corner-image:,border-top-left-image,border-top-right-image,border-bottom-left-image,border-bottom-right-image,round,stretch,border-top-left-radius:,border-top-right-radius:,border-bottom-right-radius:,border-bottom-left-radius:,inset,content:,background-origin:,background-clip:,content:,background-image:, background-position:,center,bottom,bottom:,background-repeat:,no-repeat,repeat,background-attachment:,background-size:,margin:, inline-block,block,repeat-x,padding:,auto,cover,contain,rgba(,rgb(,opacity:,:hover,hsla(,text-shadow:,text-overflow:,ellipsis-word,clip,ellipsis,box-sizing:,outline-offset:,outline: ,both,overflow:,max-height,max,min-height:,min,horizontal,vertical,max-width,min-width,float:,list-style-type:,padding-left:,padding-right:,margin-right:,margin-left:,a[,p[,overflow-x,overflow-y,transition-property,transition-duration,transition-timing-function,transition-delay,all,transition-timing-function:,ease,linear,cubic-bezier(,transition-delay:,ease-in-out,margin-bottom:,padding-bottom:,margin-top:,padding-top:,-ms-,text-align:,transition: ,white,-xv-voice-volume:,x-soft,cue-after:,x-slow,voice-family:,female,x-low,speak:,spell-out,font-family:,src:,url(,font-weight:,sans-serif,arial,column-width:,column-gap:,column-count:,column-rule:,max-width:,max-height:,font-size:,rotate(,transform:,deg,source,slice,width,outset,word-wrap:,break-word,font-style:,normal,italic,oblique,translate(,scale(,skew(,matrix(,rotateY(,rotateX(,keyframes,from,to,clear:,caption-side:,animation-duration:,animation-name:,animation-timing-function:,animation-delay:,animation-iteration-count:,animation-direction:,animation-play-state:,appearance:,button,clip:rect(,cursor:,crosshair,help,wait,default,move,crosshair,e-resize,n-resize,ne-resize,nw-resize,pointer,progress,s-resize,direction:,rtl,inline,table,table-cell,list-item,table-caption,visibility:,hidden,visible,collapse,vertical-align:,text-top,sub,super,text-bottom,body,html,:focus,:target,:active,::selection{".split(",");
			new BasicContentAssist(document.getElementById("code"), words, {visible_items: 5});
			new BasicContentAssist(document.getElementById("str"), words, {visible_items: 7});
function limpiar()
{
var statusConfirm = confirm("¿Desea limpiar el CSS?"); 
            if (statusConfirm == true) 
            { 
                document.f.code.value="";
            } 
            
}